name: example
description: >
  The typesafe, reactive and lightweight SQLite abstraction for your Flutter applications.
  This is an example on how to use the library.
version: 1.0.0
homepage: https://pinchbv.github.io/floor/
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  floor:
    path: ../floor/
  sqflite_common: 2.4.5
  sqflite_common_ffi:
    git:
      url: https://github.com/dyu/sqflite
      path: sqflite_common_ffi
      ref: sqlcipher
  sqlcipher_flutter_libs:
    git:
      url: https://github.com/dyu/sqlite3.dart
      path: sqlcipher_flutter_libs
      ref: sqlcipher
  sqlite3:
    git:
      url: https://github.com/dyu/sqlite3.dart
      path: sqlite3
      ref: sqlcipher

dev_dependencies:
  analyzer: ^5.0.0
  build_runner: ^2.2.1
  floor_generator:
    path: ../floor_generator/
  flutter_test:
    sdk: flutter
